// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// IFS2D
List IFS2D(const List& transformation, const List& translation, const std::vector<int>& probability, const int& iterations, const int pixels);
RcppExport SEXP _IFSPlot_IFS2D(SEXP transformationSEXP, SEXP translationSEXP, SEXP probabilitySEXP, SEXP iterationsSEXP, SEXP pixelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type transformation(transformationSEXP);
    Rcpp::traits::input_parameter< const List& >::type translation(translationSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type probability(probabilitySEXP);
    Rcpp::traits::input_parameter< const int& >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< const int >::type pixels(pixelsSEXP);
    rcpp_result_gen = Rcpp::wrap(IFS2D(transformation, translation, probability, iterations, pixels));
    return rcpp_result_gen;
END_RCPP
}
// IFS3D
List IFS3D(const List& transformation, const List& translation, const std::vector<int>& probability, const int& iterations, const int pixels);
RcppExport SEXP _IFSPlot_IFS3D(SEXP transformationSEXP, SEXP translationSEXP, SEXP probabilitySEXP, SEXP iterationsSEXP, SEXP pixelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type transformation(transformationSEXP);
    Rcpp::traits::input_parameter< const List& >::type translation(translationSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type probability(probabilitySEXP);
    Rcpp::traits::input_parameter< const int& >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< const int >::type pixels(pixelsSEXP);
    rcpp_result_gen = Rcpp::wrap(IFS3D(transformation, translation, probability, iterations, pixels));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IFSPlot_IFS2D", (DL_FUNC) &_IFSPlot_IFS2D, 5},
    {"_IFSPlot_IFS3D", (DL_FUNC) &_IFSPlot_IFS3D, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_IFSPlot(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
