# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IFS <- function(transformation, translation, probability, iterations, pixels) {
    .Call(`_IFSPlot_IFS`, transformation, translation, probability, iterations, pixels)
}

